### ISSUE TITLE
implement /status endpoint for server

### ISSUE THREAD

**Issue by webervin** [depesz/explain.depesz.com#11]
something that accepts request, attempts to select 1 from configured database to ensure connectivity and returns 200 only if it was truly ok.

**Comment by depesz** [comment]
So basically /history?

**Comment by webervin** [comment]
...history with body that would fit into sms would be much better. 
so simply 'ok' by default or 'database error type' if not ok.

**Comment by depesz** [comment]
this repo is migrated to gitlab: https://gitlab.com/depesz/explain.depesz.com, and all new code (including solution to this issue) will be only there.
