### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by laskin82** [depesz/explain.depesz.com#6]
trying to paste table name in UTF-8 
![default](https://cloud.githubusercontent.com/assets/16285422/22727131/420b360e-ede8-11e6-94cb-65cb1268636f.png)

**Comment by depesz** [comment]
Thanks for report, will be fixing it today.

**Comment by depesz** [comment]
Bug removed (in e289a74ccb0f7477868fc7e448ec46bb58eb07d0), deployed on explain.depesz.com site. Thanks again.
